source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0.preview2'

gem 'parallel'
gem 'rubocop', require: false
# gem 'irbtools', require: 'irbtools/binding'
gem 'pry'
gem 'pry-doc'
gem 'pry-gem', '~> 1.0'
